### PR TITLE
Code reviews

### PR DESCRIPTION
**Pull request by samnang**
1. Change indentation to 4 spaces
2. Re-order code layout
3. All state variables should be private and they should be prefix by `_`
4. Add NatSpec documentation.

## 1. Change indentation to 4 spaces
Followed https://docs.soliditylang.org/en/v0.8.15/style-guide.html#indentation

## 2. Re-order code layout
Follow these:

https://docs.soliditylang.org/en/v0.8.15/style-guide.html#order-of-functions
https://docs.soliditylang.org/en/v0.8.15/style-guide.html#order-of-layout

## 3. All state variables should be private and they should be prefix by `_`
Followed https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/GUIDELINES.md#solidity-code

The benefit from defining storage variables is public because solidity compiler will define public getters automatically for us, but there are some drawbacks from violent encapsulation. It's hard for the client to know what function signature to call, especially when those variables are in complex data types such as `mapping`. Some of those getters are not necessary by the client, and when we needed, we could define `external` getters ourselves.

## 4. Add NatSpec documentation
Followed https://docs.soliditylang.org/en/v0.8.15/natspec-format.html

### CODE REVIEW

**Review by mnm458 — APPROVED** [review]
It looks good to me, no major issues

**Review by phonsoswag — COMMENTED** [review]
Only comment (discussed during our call) would be the possible trade-offs in gas for explicitly creating getter functions for private variables, instead of the the automatic getter function that is created for public variables. Other than that, all other changes provide better readability for the overall flow of the code!

**Comment by samnang** [comment]
Thank you guys for the feedbacks.

**Comment by ch-sereyboth** [comment]
It's all good. No issues for me.

**Review by ch-sereyboth — COMMENTED** [review]
It's all good. No issues for me.

**Pull request merged**
